### ISSUE TITLE
erors while i runned the app.py file

### ISSUE THREAD

**Issue by Anuj39811** [Ajisco/ai-finance#1]
FLASK_APP = app.py
FLASK_ENV = development
FLASK_DEBUG = 0
In folder C:/Users/hp/PycharmProjects/ai-financee
C:\Users\hp\PycharmProjects\ai-financee\.venv\Scripts\python.exe -m flask run 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\hp\PycharmProjects\ai-financee\.venv\Lib\site-packages\flask\__main__.py", line 3, in <module>
    main()
  File "C:\Users\hp\PycharmProjects\ai-financee\.venv\Lib\site-packages\flask\cli.py", line 1105, in main
    cli.main()
  File "C:\Users\hp\PycharmProjects\ai-financee\.venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\hp\PycharmProjects\ai-financee\.venv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\PycharmProjects\ai-financee\.venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\PycharmProjects\ai-financee\.venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\PycharmProjects\ai-financee\.venv\Lib\site-packages\click\decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\PycharmProjects\ai-financee\.venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\PycharmProjects\ai-financee\.venv\Lib\site-packages\flask\cli.py", line 953, in run_command
    raise e from None
  File "C:\Users\hp\PycharmProjects\ai-financee\.venv\Lib\site-packages\flask\cli.py", line 937, in run_command
    app: WSGIApplication = info.load_app()
                           ^^^^^^^^^^^^^^^
  File "C:\Users\hp\PycharmProjects\ai-financee\.venv\Lib\site-packages\flask\cli.py", line 335, in load_app
    app = locate_app(import_name, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\PycharmProjects\ai-financee\.venv\Lib\site-packages\flask\cli.py", line 245, in locate_app
    __import__(module_name)
  File "C:\Users\hp\PycharmProjects\ai-financee\app.py", line 23, in <module>
    client = OpenAI(api_key=os.getenv('OPENAI_API_KEY'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\PycharmProjects\ai-financee\.venv\Lib\site-packages\openai\_client.py", line 105, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

Process finished with exit code 1

**Comment by genzsde** [comment]
I'm facing the same issue.
